
service: covid-new-cases
frameworkVersion: '2'
# package:
#   individually: true
#   exclude:
#     - a/**
plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: eu-west-2
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:PutObject'
      Resource:
        - "arn:aws:s3:::covid-cases/*"

  s3:
    covidBucket:
      name: covid-cases




functions:
  covid-cases:
    handler: handler.handle
    environment:
      COVID_CASES_API: https://api.coronavirus.data.gov.uk/v1/data?filters=areaType=nation;areaName=england&structure={%22date%22:%22date%22,%22newCases%22:%22newCasesByPublishDate%22}
    events:
      - s3:
          bucket: covidBucket
      - schedule:
          rate: rate(5 minutes)
    package:
      include:
        - lib/*.*


custom:
  pythonRequirements:
    pythonBin: python3
